### PR TITLE
chore: QArt Fashion added

### PR DESCRIPTION
**Pull request by vrijraj**

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
Please, while adding a new entry, at the end of the list.

**Comment by nimitbhargava** [comment]
@Vrijraj Can you move your addition at the bottom of the list as @vinayakkulkarni mentioned?

**Comment by nimitbhargava** [comment]
@Vrijraj 

We have updated the structure little bit since the time you shared the PR
Can you please add company in the [alphabetical order](https://github.com/vuejs-in/companies-using-vuejs-in-India#companies-in-alphabetical-order)?

**Comment by nimitbhargava** [comment]
@Vrijraj 

I updated and merged your PR.
Thanks for contributing.

**Pull request merged**
